name: FilmSimulationMemo

options:
    deploymentTarget:
        iOS: 15.0
    developmentLanguage: ja

settings:
    base:
        CODE_SIGN_STYLE: Automatic
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        OTHER_LDFLAGS: $(inherited) $(OTHER_LDFLAGS) -ObjC
        INFOPLIST_FILE: $TARGET_NAME/Info.plist
        ENABLE_BITCODE: No
        MARKETING_VERSION: 1.0.0

targets:
    Application:
        type: application
        platform: iOS
        sources: [Application]
        attributes:
            ProvisioningStyle: Automatic
        settings:
            configs:
                Debug:
                    PRODUCT_NAME: (Dev)FilmSimulationMemo
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
                    PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.FilmSimulationMemo.dev
                Release:
                    PRODUCT_NAME: FilmSimulationMemo
                    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
                    PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.FilmSimulationMemo
        dependencies:
            - target: Presentation
            - target: Domain
            - target: DataStore
            - target: Common
        preBuildScripts:
            - script: |
                # Apple Silicon MacでHomebrewのPATHが通っていなければ通す
                if [ -d /opt/homebrew/bin ] && ! type brew > /dev/null 2>&1 ; then
                    export PATH="$PATH:/opt/homebrew/bin"
                fi
                xcrun --sdk macosx mint run swiftlint --fix --format
                xcrun --sdk macosx mint run swiftlint
              name: SwiftLint

    Presentation:
        type: framework
        platform: iOS
        sources: [Presentation]
        settings:
            configs:
                Debug:
                    PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.FilmSimulationMemo.dev.Presentation
                Release:
                    PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.FilmSimulationMemo.Presentation
        dependencies:
            - target: Domain
            - target: Common

    Domain:
        type: framework
        platform: iOS
        sources: [Domain]
        settings:
            configs:
                Debug:
                    PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.FilmSimulationMemo.dev.Domain
                Release:
                    PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.FilmSimulationMemo.Domain
        dependencies:
            - target: DataStore
            - target: Common

    DataStore:
        type: framework
        platform: iOS
        sources: [DataStore]
        settings:
            configs:
                Debug:
                    PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.FilmSimulationMemo.dev.DataStore
                Release:
                    PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.FilmSimulationMemo.DataStore
        dependencies:
            - target: Common

    Common:
        type: framework
        platform: iOS
        sources: [Common]
        settings:
            configs:
                Debug:
                    PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.FilmSimulationMemo.dev.Common
                Release:
                    PRODUCT_BUNDLE_IDENTIFIER: com.shumpei.nagata.FilmSimulationMemo.Common

schemes:
    FilmSimulationMemo-Debug:
        build:
            targets:
                Application: all
        run:
            config: Debug
        test:
            config: Debug
        profile:
            config: Debug
        analyze:
            config: Debug
        archive:
            config: Debug